<a href="https://colab.research.google.com/github/YashwanthMN1/machine-learning/blob/main/project_random_forest_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
data = pd.read_csv('salary,satisfaction.csv',encoding='latin1')

In [2]:
null_columns = data.columns[data.isnull().any()]
sum = data[null_columns].isnull().sum()
print(sum.sort_values(ascending=False))
print(sum.shape)

TimeAfterBootcamp             2725
next_pymnt_d                  2610
PHONE                         2231
emp_length                    2231
HackathonReasons              2097
Hours/Shift                   2062
FrameworkWorkedWith           1313
FrameworkDesireNextYear       1215
SelfTaughtTypes               1134
DatabaseDesireNextYear        1115
Additional Information        1092
PlatformDesireNextYear        1037
Email                         1005
Methodology                    955
AIDangerous                    946
CommunicationTools             923
Age                            919
TimeFullyProductive            894
AIResponsible                  876
PlatformWorkedWith             876
AIInteresting                  870
UpdateCV                       857
EducationTypes                 818
DatabaseWorkedWith             816
AgreeDisagree2                 813
AgreeDisagree1                 813
AgreeDisagree3                 807
AIFuture                       750
LanguageDesireNextYear         667
CheckInCode                    627
VersionControl                 614
IDE                            586
OperatingSystem                569
website                        547
officeaddress                  539
LanguageWorkedWith             499
HopeFiveYears                  469
LastNewJob                     447
JobSearchStatus                435
YearsCodingProf                408
Preferred Skills               393
UndergradMajor                 322
latitude                       317
homeaddress                    317
longitude                      317
title                           64
FormalEducation                 52
DevType                         45
Minimum Qual Requirements       20
Process Date                     4
Posting Updated                  4
Posting Date                     4
Residency Requirement            4
YearsCoding                      3
your_favoritearticle_today       1
To Apply                         1
dtype: int64
(56,)

In [3]:
data.head(5)

         id  Target_Salary  ...          phones CrimeTime
0  68407277       42405.00  ...  (510) 528-2375  23:30:00
1  68355089       60740.00  ...  (510) 528-2375  23:00:00
2  68341763       51907.68  ...  (510) 528-2375  22:53:00
3  66310712       51907.68  ...  (510) 528-2375  22:50:00
4  68476807          35.00  ...  (510) 528-2375  22:31:00

[5 rows x 83 columns]

In [4]:
#checking and removing duplicate entries
print(data.shape)
data.drop_duplicates(subset='id')
print(data.shape)

(2946, 83)
(2946, 83)

In [5]:
lst = []

#converting all values into float
for i  in data['LOAN_AMT'].astype(str):
  i = str(i).replace(',','')
  lst.append(float(i[1:-1]))

#changing inplace of original data
data['LOAN_AMT'] = lst

In [6]:
#im using label encoder for encoding rather than one hot encoding 
#because it create more columns and require more computational power

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

columns_needed = ['FormalEducation','UndergradMajor','CompanySize','YearsCoding',
'YearsCodingProf','HopeFiveYears','JobSearchStatus',
'LastNewJob','UpdateCV','TimeFullyProductive','TimeAfterBootcamp',
'HackathonReasons','AgreeDisagree1','AgreeDisagree2','AgreeDisagree3',
'OperatingSystem','CheckInCode','AIDangerous','AIInteresting','AIResponsible',
'AIFuture','Age','term','loan_status','purpose','title','emp_length']


for i in columns_needed:
  data[i] = le.fit_transform(data[i].astype(str))

In [7]:
target = data['Target_Satisfied']
features = data[columns_needed]

In [8]:
# features.fillna(0)
len(columns_needed)

27

In [9]:
#classification
#importing necessary libraries
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score

#splitting data into training and testing set
X_train, X_test, y_train, y_test = train_test_split(features,target,test_size = 0.2,random_state = 7)

#scaling data
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


#model building
class_model = RandomForestClassifier(n_estimators = 500,criterion= 'gini')
class_model.fit(X_train,y_train)
class_pred = class_model.predict(X_test)

#printing model scores
print('classification model score for training set is ==>',class_model.score(X_train,y_train))
print('classification model score for testing set is  ==>',class_model.score(X_test,y_test),'\n','\n')

#printing root mean squared error
print('f1 score for classification model predictions is ==>',f1_score(y_test,class_pred))

classification model score for training set is ==> 0.9995755517826825
classification model score for testing set is  ==> 0.8033898305084746


f1 score for classification model predictions is ==> 0.03333333333333333